### ISSUE TITLE
Define commands in separate file

### ISSUE THREAD

**Issue by lonix1** [AnWeber/vscode-statusbar-command#29]
I defined items in my `.vscode/settings.json` and it works well.

But is it possible to define the config in a separate file? e.g. `.vscode/statusbar.json`? That is convenient because it would be decoupled from the vscode config (which we have in source control).

**Comment by AnWeber** [comment]
There is a new setting which supports configuration of a external file. 
<img width="272" alt="image" src="https://github.com/AnWeber/vscode-statusbar-command/assets/13434739/c7cc428f-42ff-4b35-b660-9f2aaca440b5">

I expect a array of commands in this file. Update to the file are immediatly updated in VSCode

**Comment by AnWeber** [comment]
> Thirdly, I couldn't get it to work.

The path must be absolute, because it is not workspace dependent. You should get an error listed in output of statusbar_commands
![works](https://github.com/AnWeber/vscode-statusbar-command/assets/13434739/82bcd470-2b32-48e3-9779-6b21740b4dfd)

> Secondly, it was very sad to learn that it's only available for "application settings"

I may not understand the use case yet. It is always possible to have one .vscode/settings.json per workspace, which is then also committed. If you commit now only the special statusbarcommands.json it would not work without the extra entry in the workspace settings. For me the workspace settings are always more or less empty, what sense does it make to build such a construct here?

**Comment by itldg** [comment]
I also have this requirement. I think having a separate file for configuration would be better. I found this option, but after reading this issue, I realized that it must be an absolute path. However, I think a relative path like 'vscode-commander' is better

![file](https://github.com/ppatotski/vscode-commandbar/raw/master/getstarted.gif)
